### ISSUE TITLE
Exited with status 1     at closeArgsToError

### ISSUE THREAD

**Issue by avh4** [jfmengels/node-elm-review#20] opened 2020-10-07 17:45 UTC
```
$ node --version
v14.8.0
$ npm --version
6.14.7
$ mkdir example
$ cd example
$ echo {} > package.json
$ npm install --save-dev elm-review
...
$ npx elm-review --help
You are using elm-review 2.3.3.
...
$ npx elm-review new-package
✔ Your GitHub username: … avh4-experimental
✔ The package name (starting with "elm-review-"): … elm-review-module-organization
✔ The license for your package: … MIT
✔ Name of the rule (ex: No.Doing.Foo): … CodeOrganization.ManipulationFunctionsLiveWithTheirType
✔ Adding elm.json
✔ Adding package.json
✔ Adding README
✖ Adding preview folder
-- UNEXPECTED ERROR ------------------------------------------------------------

I ran into an unexpected error. Please open an issue at the following link:
  https://github.com/jfmengels/node-elm-review/issues/new

Please include this error message and as much detail as you can provide. If you
can, please provide a setup that makes it easy to reproduce the error. That will
make it much easier to fix the issue.

Below is the error that was encountered.
--------------------------------------------------------------------------------
Error: Exited with status 1
    at closeArgsToError (/Users/av/workspace/elm-review-module-organization/node_modules/cross-spawn-promise/lib/index.js:20:16)
    at ChildProcess.<anonymous> (/Users/av/workspace/elm-review-module-organization/node_modules/cross-spawn-promise/lib/index.js:76:19)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

**Comment by avh4** [comment] 2020-10-07 17:54
Also fails in the same way with:

```
$ node --version
v14.5.0
$ npm --version
6.14.5
$ npx elm-review@v2.3.3 new-package
✔ Your GitHub username: … avh4-experimental
✔ The package name (starting with "elm-review-"): … elm-review-module-organization
✔ The license for your package: … MIT
✔ Name of the rule (ex: No.Doing.Foo): … CodeOrganization.ManipulationFunctionsLiveWithTheirType
✔ Adding elm.json
✔ Adding package.json
✔ Adding README
✖ Adding preview folder
-- UNEXPECTED ERROR ------------------------------------------------------------

I ran into an unexpected error. Please open an issue at the following link:
  https://github.com/jfmengels/node-elm-review/issues/new

Please include this error message and as much detail as you can provide. If you
can, please provide a setup that makes it easy to reproduce the error. That will
make it much easier to fix the issue.

Below is the error that was encountered.
--------------------------------------------------------------------------------
Error: Exited with status 1
    at closeArgsToError (/Users/av/.npm/_npx/755/lib/node_modules/elm-review/node_modules/cross-spawn-promise/lib/index.js:20:16)
    at ChildProcess.<anonymous> (/Users/av/.npm/_npx/755/lib/node_modules/elm-review/node_modules/cross-spawn-promise/lib/index.js:76:19)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

**Comment by vstene** [comment] 2020-10-20 12:28
Experiencing the same on a non-root user. Looks like it's a file/directory permission issue, not figured out it yet.

**Comment by vstene** [comment] 2020-10-30 09:32
In my situation `~/.elm` was owned by root, but the user executing the command was not root.
Deleted the `~/.elm` folder on this user.

**Comment by jfmengels** [comment] 2022-08-21 08:59
Sorry for not replying to this issue earlier. I know that I had tried reproducing the issue when the issue was reported but forgot to write about it (I hoped I could find a way to reproduce it).

I'm going to close the issue because a lot of changes have happened in the repo since the issue was created. But **please** open a new issue if you still run into this :pray:

**Closed by jfmengels** 2022-08-21 08:59 UTC
