### ISSUE TITLE
elm-review --fix crashes on a certain operation

### ISSUE THREAD

**Issue by r-k-b** [jfmengels/node-elm-review#60] opened 2021-10-02 07:39 UTC
I was able to `--fix` a few previous occurrences, but this one consistently fails:

<details><summary>"I ran into an unexpected error"</summary>

```shell
[rkb@nixos:~/projects/tularstmp]$ elm-review --fix
-- ELM-REVIEW ERROR ----------------------------------------- app/Main.elm:587:7

NoUnsortedRecords: Record fields are not sorted.

586|     in
587|     ( { agent
           ^
588|         | physics = newPhysics

Record fields were found out of order.  They should be sorted as specified in
the rule configuration.

I think I can fix this. Here is my proposal:

 588|         | physics = newPhysics
 589|         , topActionLastStartTimes = newTopActionLastStartTimes
 590|         , callingOut = newCall
 591|         , hunger = newHunger
 592|         , currentAction = topAction |> Maybe.map .name |> withDefault "none"
 593|         , currentOutcome = newOutcome
 594|         , holding = newHolding
 595|         , beggingForFood = beggingForFood
 596|         , hp = hitpointsAfterStarvation
 597|         , currentAction = topAction |> Maybe.map .name |> withDefault "none", currentOutcome = newOutcome, hunger = newHunger
 597|         , beggingForFood = beggingForFood, topActionLastStartTimes = newTopActionLastStartTimes, callingOut = newCall, holding = newHolding, hp = hitpointsAfterStarvation
 597|       }

✔ Do you wish to apply this fix? … yes

-- UNEXPECTED ERROR ------------------------------------------------------------

I ran into an unexpected error. Please open an issue at the following link:
  https://github.com/jfmengels/node-elm-review/issues/new

Please include this error message and as much detail as you can provide. If you
can, please provide a setup that makes it easy to reproduce the error. That will
make it much easier to fix the issue.

Below is the error that was encountered.
--------------------------------------------------------------------------------
Error: https://github.com/elm/core/blob/1.0.0/hints/5.md
    at _Debug_crash (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:460:8)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:554:30)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:587:8)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:587:8)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:587:8)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:587:8)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:587:8)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:587:8)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:587:8)
    at _Utils_eqHelp (/home/rkb/projects/tularstmp/elm-stuff/generated-code/jfmengels/elm-review/cli/2.5.5/review-applications/3835e632b06db71195022df297a481d6.js:587:8)
```

</details>

# repro

```shell
$ git clone git@github.com:r-k-b/tulars.git

$ cd tulars

$ git checkout 424d21546444e1642de657f02874485814e5fae8

$ node --version
v14.17.6

$ npm i

$ elm-review --version
2.5.5

$ elm-review --fix
```

Hit `Y`, then crashes like the one shown above happen. It will crash the next few times too, but on different reported problems.

**Comment by jfmengels** [comment] 2021-10-02 08:18
Hi @r-k-b, thanks for the detailed issue, I was able to reproduce it.

I think the issue is that you are using `NoUnsortedRecords` (cc @SiriusStarr), which contains functions in its `ProjectContext`. Having functions in the project contexts can create problems because in watch mode and in fix mode we compare project contexts using `==` to know whether something needs to be recomputed or not.

It's unfortunately something I can't enforce using Elm's type system. I did try to document it functions like [this one](https://package.elm-lang.org/packages/jfmengels/elm-review/latest/Review-Rule#newProjectRuleSchema) (see the **Note**) but considering the size of the documentation, I'm not surprised that this appeared at one point or another.

The best course of action is to [open an issue in the repo](https://github.com/SiriusStarr/elm-review-no-unsorted/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). I'll close the issue since I don't think there's anything actionable I can do on my side, but feel free to continue discussing the issue here, or ways that we can improve this.

**Closed by jfmengels** 2021-10-02 08:18 UTC

**Comment by SiriusStarr** [comment] 2021-10-02 22:04
I somehow managed to never read that line in the docs, whoops...

Might be good to either have a review rule in the default package to check for `Eq`, or if there could be a default test added?  IDK how many more people might miss that section of the docs, but it would be good to catch it, since it won't crop up in many cases until it's a problem.  Either might be non-trivial to implement, however.

**Comment by jfmengels** [comment] 2021-10-03 08:27
There have been proposals about reporting functions in types like `Model`, which I think would work here as well. I think it would be quite do-able, though there will be a knowledge gap when it comes to opaque types from dependencies, and there you'll have to ignore the issues, or ask the `elm-review` user for a list of types from dependencies known to contain functions.

Though the easiest would be for us to wait until Elm has an `equatable` type class (like `comparable`), which from my understanding is something that they're planning to have in a future version.
